menu:
  Home: /
  Archives: /archives
  About: /about

# gitment
gitment: false
gitment_owner:
gitment_repo:
gitment_client_id:
gitment_client_secret:

# disqus comment
disqus: boolean
disqus_shortname: whamwong-blog

# google analytics
googleTrackId:
